//###########################################################################
//
// FILE:   main.c
//
// TITLE:  F280049C LaunchPad serial plotter
//
// DAC A drives a 256-step sine on DACOUTA. ADC A samples that same pin
// (ADCINA0) and SCIA streams "dac,adc" lines at 500 Hz. Polling only.
// Watchdog is disabled by codestart (WD_DISABLE) and again by InitSysCtrl().
//
//###########################################################################

#include "F28x_Project.h"

//
// SYSCLK = 10 MHz XTAL * IMULT_10 / PLLCLK_BY_2 = 100 MHz.
// InitSysCtrl() / InitPeripheralClocks() never write ClkCfgRegs.LOSPCP.
// LSPCLKDIV reset value is 2, which driverlib documents as
// SYSCTL_LSPCLK_PRESCALE_4 (default): LSPCLK = SYSCLK / 4 = 25 MHz.
// driverlib SysCtl_getLowSpeedClock() divides by (2 * LSPCLKDIV) when
// LSPCLKDIV != 0, which is the same /4.
//
// BRR = LSPCLK / (baud * 8) - 1
//     = 25000000 / (115200 * 8) - 1
//     = 27.1267... - 1
//     = 26.1267...
// Integer division truncates 25000000/921600 to 27, then subtracts 1,
// so the programmed BRR is 26 (0x001A). Same constant as the LaunchPad
// demo (SCIHBAUD = 0x00, SCILBAUD = 0x1A).
//
// Actual baud = 25000000 / ((26 + 1) * 8) = 115740.74 Hz
// Error = (115740.74 - 115200) / 115200 = +0.469%
//
#define SYSCLK_HZ            100000000UL
#define LSPCLK_DIV           4UL
#define LSPCLK_HZ            (SYSCLK_HZ / LSPCLK_DIV)
#define SCIA_BAUD_TARGET     115200UL
#define SCIA_BRR             ((LSPCLK_HZ / (SCIA_BAUD_TARGET * 8UL)) - 1UL)

#if (SCIA_BRR != 26)
#error "SCIA_BRR is not 26; check LSPCLK or the baud formula"
#endif

//
// CPU Timer0 counts SYSCLK. A period of (PRD + 1) cycles is exactly 2 ms
// when PRD = 100e6/500 - 1 = 199999. TIF is polled; the timer interrupt
// enable stays off.
//
#define SAMPLE_HZ            500UL
#define TIMER0_PRD           ((SYSCLK_HZ / SAMPLE_HZ) - 1UL)

#if (TIMER0_PRD != 199999UL)
#error "TIMER0_PRD is not 199999; sample period is not 2 ms"
#endif

#define SINE_SAMPLES         256U
#define SINE_MID             2048U

//
// Reference choice (0-3.3 V full scale on both ADC A and DAC A, no
// external reference and no jumper):
//
// 1. LaunchPad SPRUII7B section 2.1.8: VREFHIx is either driven externally
//    on header J15 or generated by the internal bandgap. J15 is optional,
//    so the internal bandgap is the no-parts path.
// 2. adc_ex1_soc_epwm.c calls
//    SetVREF(ADC_ADCA, ADC_INTERNAL, ADC_VREF3P3).
//    f28004x_adc_defines.h: ADC_INTERNAL=0, ADC_VREF3P3=0.
//    SetVREF writes ANAREFASEL=0 (internal) and ANAREFA2P5SEL=0, and the
//    function comment says that pair selects the "Internal / 1.65v mode"
//    offset trim. driverlib asysctl.h ASysCtl_setAnalogReference1P65()
//    clears the same ANAREFCTL bit (reference << 8). The ADC full-scale
//    name for that mode is 3.3 V (driverlib ADC_REFERENCE_3_3V = 0).
// 3. DACCTL.DACREFSEL = 1 selects the ADC VREFHI node, not the VDAC pin.
//    driverlib dac.h: DAC_REF_VDAC=0, DAC_REF_ADC_VREFHI=1.
//    dac_ex1_enable.c defaults to REFERENCE_VDAC and says an external
//    3.3 V wire must be tied to ADCINB3/VDAC. That path is not used here.
// 4. With DACREFSEL=1 and the ADC internal reference, DACCTL.MODE is the
//    buffer gain. driverlib dac.h: DAC_GAIN_ONE=0, DAC_GAIN_TWO=2.
//    DAC_CTL_MODE is 0x2, so the bitfield MODE=1 is the x2 gain.
//    The same header notes that MODE is used only for the internal
//    VREFHI reference. x2 turns the 1.65 V internal reference into a
//    0-3.3 V DAC span, which matches the ADC 3.3 V full scale.
//    GPIO_EX1 Init_DAC uses this same MODE=1 / DACREFSEL=1 pair.
// 5. ADCINA0 and DACOUTA are the same pin (dac_ex1: "DACOUTA/ADCINA0").
//    No GPIO mux and no board wire.
//
// ADCCLK: adc_ex1 sets ADCCTL2.PRESCALE = 6 and comments "divider to /4".
// driverlib ADC_CLK_DIV_4_0 = 6. At SYSCLK = 100 MHz, ADCCLK = 25 MHz.
//
// ACQPS = 63 -> sample window (63 + 1) SYSCLK = 640 ns, long enough for
// the buffered DAC output impedance on the shared pin.
//

#pragma DATA_SECTION(sineTable, ".econst")
const Uint16 sineTable[SINE_SAMPLES] =
{
    2048, 2089, 2130, 2171, 2212, 2253, 2293, 2334, 2374, 2415, 2455, 2494, 2534, 2573, 2612, 2650,
    2689, 2726, 2764, 2801, 2837, 2873, 2909, 2944, 2978, 3012, 3045, 3078, 3110, 3142, 3173, 3203,
    3232, 3261, 3289, 3316, 3342, 3368, 3393, 3417, 3440, 3463, 3484, 3505, 3525, 3544, 3562, 3579,
    3595, 3610, 3625, 3638, 3651, 3662, 3673, 3682, 3691, 3698, 3705, 3710, 3715, 3718, 3721, 3722,
    3723, 3722, 3721, 3718, 3715, 3710, 3705, 3698, 3691, 3682, 3673, 3662, 3651, 3638, 3625, 3610,
    3595, 3579, 3562, 3544, 3525, 3505, 3484, 3463, 3440, 3417, 3393, 3368, 3342, 3316, 3289, 3261,
    3232, 3203, 3173, 3142, 3110, 3078, 3045, 3012, 2978, 2944, 2909, 2873, 2837, 2801, 2764, 2726,
    2689, 2650, 2612, 2573, 2534, 2494, 2455, 2415, 2374, 2334, 2293, 2253, 2212, 2171, 2130, 2089,
    2048, 2006, 1965, 1924, 1883, 1842, 1802, 1761, 1721, 1680, 1640, 1601, 1561, 1522, 1483, 1445,
    1406, 1369, 1331, 1294, 1258, 1222, 1186, 1151, 1117, 1083, 1050, 1017, 985, 953, 922, 892,
    863, 834, 806, 779, 753, 727, 702, 678, 655, 632, 611, 590, 570, 551, 533, 516,
    500, 485, 470, 457, 444, 433, 422, 413, 404, 397, 390, 385, 380, 377, 374, 373,
    372, 373, 374, 377, 380, 385, 390, 397, 404, 413, 422, 433, 444, 457, 470, 485,
    500, 516, 533, 551, 570, 590, 611, 632, 655, 678, 702, 727, 753, 779, 806, 834,
    863, 892, 922, 953, 985, 1017, 1050, 1083, 1117, 1151, 1186, 1222, 1258, 1294, 1331, 1369,
    1406, 1445, 1483, 1522, 1561, 1601, 1640, 1680, 1721, 1761, 1802, 1842, 1883, 1924, 1965, 2006
};

static void Sci_Config(volatile struct SCI_REGS *sci);
static void Sci_SendByte(volatile struct SCI_REGS *sci, Uint16 data);
static void SciA_SendString(const char *msg);
static void SciA_SendU16(Uint16 value);
static void SciA_Init(void);
static void AdcA_Init(void);
static void DacA_Init(void);
static void Timer0_Init(void);
static Uint16 AdcA_ReadA0(void);
static void Stream_SendSample(Uint16 dacCode, Uint16 adcCode);

static void Sci_Config(volatile struct SCI_REGS *sci)
{
    // FIFO on, both FIFOs out of reset. 0xE040 / 0x2044 match the
    // proven C2000Ware SCI FIFO loopback init (SCIRST, SCIFFENA,
    // TXFIFORESET, RXFIFORESET, interrupt flags cleared).
    sci->SCIFFTX.all = 0xE040;
    sci->SCIFFRX.all = 0x2044;
    sci->SCIFFCT.all = 0x0000;

    // 8 data bits, idle-line, no parity, 1 stop. Loopback stays off.
    sci->SCICCR.all = 0x0007;
    // TX and RX enabled, SCI held in software reset.
    sci->SCICTL1.all = 0x0003;
    // Polling only: receiver and transmitter interrupts stay off.
    sci->SCICTL2.all = 0x0000;

    sci->SCIHBAUD.all = (Uint16)((SCIA_BRR >> 8) & 0x00FFU);
    sci->SCILBAUD.all = (Uint16)(SCIA_BRR & 0x00FFU);

    sci->SCICCR.bit.LOOPBKENA = 0;

    // Release software reset. TXENA and RXENA stay set.
    sci->SCICTL1.all = 0x0023;
}

//
// TX FIFO is 16 deep. A sample line is at most 10 bytes ("3723,3723\n")
// and takes about 0.87 ms at 115200 8N1, under the 2 ms tick. The FIFO
// therefore stays well below full. If it is full, spin until a slot
// opens so a byte is never dropped.
//
static void Sci_SendByte(volatile struct SCI_REGS *sci, Uint16 data)
{
    while(sci->SCIFFTX.bit.TXFFST >= 16U)
    {
    }

    sci->SCITXBUF.all = data & 0x00FFU;
}

static void SciA_SendString(const char *msg)
{
    while(*msg != 0)
    {
        Sci_SendByte(&SciaRegs, (Uint16)(*msg) & 0x00FFU);
        msg++;
    }
}

static void SciA_SendU16(Uint16 value)
{
    char buf[5];
    Uint16 n;

    n = 0U;
    do
    {
        buf[n] = (char)('0' + (value % 10U));
        n++;
        value = (Uint16)(value / 10U);
    }
    while((value != 0U) && (n < 5U));

    while(n > 0U)
    {
        n--;
        Sci_SendByte(&SciaRegs, (Uint16)buf[n]);
    }
}

static void SciA_Init(void)
{
    // SCIA on the LaunchPad XDS110 virtual COM port:
    //   GPIO28 mux 1 = SCIRXDA, asynchronous input, pull-up enabled
    //   GPIO29 mux 1 = SCITXDA
    // 115200 8N1, FIFO enabled, loopback off.
    EALLOW;
    GpioCtrlRegs.GPAGMUX2.bit.GPIO28 = 0;
    GpioCtrlRegs.GPAMUX2.bit.GPIO28 = 1;
    GpioCtrlRegs.GPAQSEL2.bit.GPIO28 = 3;
    GpioCtrlRegs.GPAPUD.bit.GPIO28 = 0;
    GpioCtrlRegs.GPADIR.bit.GPIO28 = 0;

    GpioCtrlRegs.GPAGMUX2.bit.GPIO29 = 0;
    GpioCtrlRegs.GPAMUX2.bit.GPIO29 = 1;
    GpioCtrlRegs.GPAPUD.bit.GPIO29 = 0;
    GpioCtrlRegs.GPADIR.bit.GPIO29 = 1;
    EDIS;

    Sci_Config(&SciaRegs);
}

static void AdcA_Init(void)
{
    // Internal 1.65 V reference, ADC full scale 3.3 V. See file header.
    SetVREF(ADC_ADCA, ADC_INTERNAL, ADC_VREF3P3);

    EALLOW;
    CpuSysRegs.PCLKCR13.bit.ADC_A = 1;
    // adc_ex1: PRESCALE 6 => ADCCLK = SYSCLK / 4 = 25 MHz.
    AdcaRegs.ADCCTL2.bit.PRESCALE = 6;
    // Late interrupt pulse: ADCINT1 is set when ADCRESULT0 is latched.
    AdcaRegs.ADCCTL1.bit.INTPULSEPOS = 1;
    AdcaRegs.ADCCTL1.bit.ADCPWDNZ = 1;
    EDIS;

    DELAY_US(1000);

    EALLOW;
    // Software trigger only. Channel A0 is the DACOUTA pin.
    AdcaRegs.ADCSOC0CTL.bit.CHSEL = 0;
    AdcaRegs.ADCSOC0CTL.bit.TRIGSEL = 0;
    AdcaRegs.ADCSOC0CTL.bit.ACQPS = 63;
    AdcaRegs.ADCINTSEL1N2.bit.INT1SEL = 0;
    AdcaRegs.ADCINTSEL1N2.bit.INT1E = 1;
    AdcaRegs.ADCINTSEL1N2.bit.INT1CONT = 0;
    AdcaRegs.ADCINTFLGCLR.bit.ADCINT1 = 1;
    AdcaRegs.ADCINTOVFCLR.bit.ADCINT1 = 1;
    EDIS;
}

static void DacA_Init(void)
{
    EALLOW;
    CpuSysRegs.PCLKCR16.bit.DAC_A = 1;
    // Load DACVALA from DACVALS on the next SYSCLK.
    DacaRegs.DACCTL.bit.LOADMODE = 0;
    // x2 gain so 1.65 V internal VREFHI becomes a 0-3.3 V output.
    DacaRegs.DACCTL.bit.MODE = 1;
    // Reference is ADC VREFHI, not the VDAC pin.
    DacaRegs.DACCTL.bit.DACREFSEL = 1;
    DacaRegs.DACOUTEN.bit.DACOUTEN = 1;
    DacaRegs.DACVALS.all = SINE_MID;
    EDIS;

    // dac_ex1 waits 10 us for the buffered DAC to power up.
    DELAY_US(10);
}

static void Timer0_Init(void)
{
    // Stop, /1 prescale, period 199999, free-run if the debugger halts.
    CpuTimer0Regs.TCR.bit.TSS = 1;
    CpuTimer0Regs.PRD.all = TIMER0_PRD;
    CpuTimer0Regs.TPR.all = 0;
    CpuTimer0Regs.TPRH.all = 0;
    // TSS=1, TRB=1, SOFT=1, FREE=1, TIE=0. Writing TIF=0 does not clear.
    CpuTimer0Regs.TCR.all = 0x0C30;
    // Write-1 clears TIF, then let the timer run.
    CpuTimer0Regs.TCR.bit.TIF = 1;
    CpuTimer0Regs.TCR.bit.TSS = 0;
}

static Uint16 AdcA_ReadA0(void)
{
    AdcaRegs.ADCSOCFRC1.bit.SOC0 = 1;

    while(AdcaRegs.ADCINTFLG.bit.ADCINT1 == 0U)
    {
    }

    AdcaRegs.ADCINTFLGCLR.bit.ADCINT1 = 1;
    if(AdcaRegs.ADCINTOVF.bit.ADCINT1 != 0U)
    {
        AdcaRegs.ADCINTOVFCLR.bit.ADCINT1 = 1;
        AdcaRegs.ADCINTFLGCLR.bit.ADCINT1 = 1;
    }

    return(AdcaResultRegs.ADCRESULT0);
}

static void Stream_SendSample(Uint16 dacCode, Uint16 adcCode)
{
    SciA_SendU16(dacCode);
    Sci_SendByte(&SciaRegs, (Uint16)',');
    SciA_SendU16(adcCode);
    Sci_SendByte(&SciaRegs, (Uint16)'\n');
}

void main(void)
{
    Uint16 index;
    Uint16 dacCode;
    Uint16 adcCode;

    InitSysCtrl();

    DINT;
    IER = 0x0000;
    IFR = 0x0000;

    AdcA_Init();
    DacA_Init();
    SciA_Init();
    Timer0_Init();

    // One legend line for the host plotter. No other text after this.
    SciA_SendString("dac,adc\n");

    index = 0U;

    for(;;)
    {
        while(CpuTimer0Regs.TCR.bit.TIF == 0U)
        {
        }
        CpuTimer0Regs.TCR.bit.TIF = 1;

        dacCode = sineTable[index];
        DacaRegs.DACVALS.all = dacCode;
        DELAY_US(20);
        adcCode = AdcA_ReadA0();
        Stream_SendSample(dacCode, adcCode);

        index++;
        if(index >= SINE_SAMPLES)
        {
            index = 0U;
        }
    }
}
